# Start from the official Go image
FROM golang:1.23

# Set the working directory inside the container
WORKDIR /app

# Install air for live reloading
RUN go install github.com/air-verse/air@latest

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies
RUN go mod download

# Copy the source code into the container
COPY . .

# Command to run air for live reloading
CMD ["air", "-c", ".air.toml"]