name: Go

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.5"

      - name: Verify directory structure
        run: |
          pwd
          ls -R
          echo "Contents of gopherService directory:"
          ls -la gopherService

      - name: Build
        run: |
          cd gopherService
          go build -v .

      - name: Test
        run: |
          cd gopherService
          go test -v ./...

      - name: Display Go version and module info
        run: |
          go version
          cd gopherService
          go list -m all
